sudo: false
language: node_js
cache:
  directories:
    - node_modules
install: travis_retry npm install
script:
  - gulp lint:js
  - gulp lint:html
  - travis_retry gulp test:mobile
  - travis_retry gulp test:desktop
  - travis_retry gulp test:shadow
