---
title: Remote and Custom Filtering
order: 8
layout: page
---


[[vaadin-combo-box.external-filtering]]
== Overview

By default, [vaadinelement]#vaadin-combo-box# is used with a local array of items
is filtered internally to display only the items that match the input that the
user has typed. The search algorithm used is a simple case insensitive search.

Next, we're going to go through how you can do filtering remotely, and also
how to customize the filtering on the client side.


== Remote Filtering

By default, the internal client side filtering is run every time user types something
on the input field. To prevent that, we need to set [propertyname]#externalFiltering#.

This not only disable the client side filtering, but also tell
[vaadinelement]#vaadin-combo-box# to remain in "loading" state until a fresh set
of pre-filtered items is reassigned to [propertyname]#items#.

You can combine these properties together with [vaadinelement]#iron-ajax# as follows:

[source,html]
----
<iron-ajax url="http://your.remote.url/?filter=[[filter]]"
           last-response={{response}}
           debounce-duration="500" auto>
</iron-ajax>

<vaadin-combo-box items="[[response]]" filter="{{filter}}" external-filtering>
</vaadin-combo-box>
----

[NOTE]
When [vaadinelement]#vaadin-combo-box# is closed, [propertyname]#filter# changes to an empty string.

== Custom Filtering

When you want to custom filtering on the client side, you can listen for changes
on the [propertyname]#filter# and update [propertyname]#items# based on any criteria.

[source,html]
----
<vaadin-combo-box items="[[items]]" on-filter-changed="_filterChanged" external-filtering>
</vaadin-combo-box>

<script>
  ...
  _filterChanged: function(e) {
    var filter = e.detail.value;
    this.items = elements.filter(function(el) {
      return el.indexOf(filter) === 0;
    });
  }
  ...
</script>
----
